#!/usr/bin/env php
<?php

require __DIR__.'/_bootstrap.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \derhasi\symlinker\Command\Symlink());
$application->run();